# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 23:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be in hex format', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('store_url', models.URLField(null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.FileField(upload_to='icons/platforms/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be in hex format', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('subtitle', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Platform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='app',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Platform'),
        ),
    ]
