# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 19:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be in hex format', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('publish_date', models.DateField()),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Platform')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
